module.exports = {
  env: {
    es6: true,
    jest: true,
  },
  extends: 'airbnb',
  globals: {},
  parser: 'babel-eslint',
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 2018,
    sourceType: 'module',
  },
  plugins: [
    'react',
    'react-hooks',
  ],
  settings: {
    'import/resolver': {
      'babel-module': {},
    },
  },
  rules: {
    'arrow-body-style': ['error', 'as-needed'],
    'import/no-extraneous-dependencies': 0,
    'import/no-named-as-default-member': 0,
    'import/no-default-export': 'error',
    'import/prefer-default-export': 0,
    'jsx-a11y/anchor-has-content': 0,
    'jsx-a11y/anchor-is-valid': 'warn',
    'jsx-a11y/click-events-have-key-events': 0,
    'jsx-a11y/label-has-associated-control': 0,
    'jsx-a11y/label-has-for': 0,
    'jsx-a11y/mouse-events-have-key-events': 0,
    'jsx-a11y/no-noninteractive-tabindex': 0,
    'jsx-a11y/no-static-element-interactions': 0,
    indent: ['error', 2],
    'max-len': ['error', { code: 160 }],
    'no-shadow': 0,
    'object-curly-newline': 0,
    'react-hooks/exhaustive-deps': 0,
    'react-hooks/rules-of-hooks': 'error',
    'react/button-has-type': 0,
    'react/forbid-foreign-prop-types': 0,
    'react/jsx-filename-extension': 0,
    'react/no-array-index-key': 0,
    'react/no-find-dom-node': 0,
    'react/no-string-refs': 0,
    'react/prefer-stateless-function': 'warn',
    'react/jsx-props-no-spreading': 0,
    semi: ['error', 'always'],
    'react/jsx-fragments': [2, 'element'],
  },
};
