/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

export const FinancialGrey1 = () : string => `<svg xmlns="http://www.w3.org/2000/svg" width="20.846" height="22.318" viewBox="0 0 20.846 22.318">
  <g id="Group_13" data-name="Group 13" transform="translate(-225.551 -347.018)">
    <path id="Path_1" data-name="Path 1" d="M288.371,46.1c-.564-1.907-1.152-3.807-1.734-5.726l.53-.368a3.128,3.128,0,0,0-.067-5.224,1.613,1.613,0,0,0-2.314.408c-.345.447-.672.909-.878,1.189a30.86,30.86,0,0,0-11.28.005c-.709-.706-1.012-2.34-2.664-1.836a3.146,3.146,0,0,0-2.068,2.592c-.342,1.615.707,2.483,2.009,3.18-.312,1.068-.61,2.094-.914,3.12s-.654,2.053-.924,3.094a4.739,4.739,0,0,0,2.4,5.687c2.533,1.328,5.2,3.763,7.768,4.551,2.486-.679,5.063-3.1,7.513-4.371C288.359,51.046,289.2,48.89,288.371,46.1Zm-15.178-4.819a11.432,11.432,0,0,1,1.3.008,1.546,1.546,0,0,1,1.415,2,.61.61,0,0,1-.387.395A2.235,2.235,0,0,1,273.193,41.279Zm9.455,9.164a4.462,4.462,0,0,1-8.8-1.21,6.379,6.379,0,0,1,2.456-4.449,2.848,2.848,0,0,1,3.911-.03A6.089,6.089,0,0,1,282.648,50.443Zm-1.624-6.759a.609.609,0,0,1-.387-.395,1.546,1.546,0,0,1,1.414-2,11.434,11.434,0,0,1,1.3-.008A2.235,2.235,0,0,1,281.024,43.684Z" transform="translate(-42.28 312.568)" fill="#15182c"/>
    <path id="Path_5" data-name="Path 5" d="M286.344,62.949a3.233,3.233,0,0,1-2.117-1.206,1.5,1.5,0,0,1-.012-2.086,3.1,3.1,0,0,1,4.218-.06,1.564,1.564,0,0,1-.158,2.346A3.132,3.132,0,0,1,286.344,62.949Z" transform="translate(-50.37 300.232)" fill="#15182c"/>
    <path id="Path_6" data-name="Path 6" d="M287.235,66.212a1.027,1.027,0,0,1,.192.363,1.235,1.235,0,0,1,.061.421,1.191,1.191,0,0,1-.122.506,1.116,1.116,0,0,1-.171.227.713.713,0,0,1-.223.162.69.69,0,0,1-.234.08.606.606,0,0,1-.212.014.788.788,0,0,1-.3-.063.94.94,0,0,1-.1-.046s.039-.022.1-.052a2.489,2.489,0,0,0,.243-.116,1.161,1.161,0,0,0,.265-.181.631.631,0,0,0,.106-.117.672.672,0,0,0,.088-.137,2.892,2.892,0,0,0,.216-.681C287.191,66.377,287.235,66.212,287.235,66.212Z" transform="translate(-51.549 296.476)" fill="#15182c"/>
    <path id="Path_7" data-name="Path 7" d="M288.978,66.212s.044.165.09.38a2.868,2.868,0,0,0,.216.681.692.692,0,0,0,.088.137.649.649,0,0,0,.107.117,1.151,1.151,0,0,0,.265.181,2.439,2.439,0,0,0,.243.116c.063.031.1.052.1.052a.943.943,0,0,1-.1.046.789.789,0,0,1-.3.063.6.6,0,0,1-.211-.014.686.686,0,0,1-.234-.08.707.707,0,0,1-.223-.162,1.115,1.115,0,0,1-.171-.227,1.19,1.19,0,0,1-.122-.506,1.235,1.235,0,0,1,.061-.421A1.018,1.018,0,0,1,288.978,66.212Z" transform="translate(-52.866 296.476)" fill="#15182c"/>
  </g>
</svg>
`;
  export const FinancialGrey10 = () : string => `<svg xmlns="http://www.w3.org/2000/svg" width="17.933" height="11.902" viewBox="0 0 17.933 11.902">
  <g id="Group_258" data-name="Group 258" transform="translate(-56.207 -462.9)">
    <g id="Group_246" data-name="Group 246" transform="translate(56.96 464)">
      <path id="Path_16" data-name="Path 16" d="M0,9.141,6.3,3.227,9.115,6.043,15.158,0" transform="translate(0 0.859)" fill="none" stroke="#fff" stroke-width="2.2"/>
      <path id="Path_17" data-name="Path 17" d="M0,0H4.164V4.479" transform="translate(11.916 0)" fill="none" stroke="#fff" stroke-width="2.2"/>
    </g>
  </g>
</svg>
`;
  export const FinancialGrey11 = () : string => `<svg xmlns="http://www.w3.org/2000/svg" width="20.072" height="18.178" viewBox="0 0 20.072 18.178">
  <g id="Group_274" data-name="Group 274" transform="translate(-41.392 -963.25)">
    <path id="Path_10" data-name="Path 10" d="M87.142,237v16.678h17.022" transform="translate(-45 727)" fill="none" stroke="#25d366" stroke-linecap="round" stroke-width="1.5"/>
    <path id="Path_11" data-name="Path 11" d="M101.147,247.63l4.671-4.671,3.555,3.555,5.754-5.754" transform="translate(-54.724 727)" fill="none" stroke="#25d366" stroke-linecap="round" stroke-width="1.5"/>
  </g>
</svg>
`;
  export const FinancialGrey12 = () : string => `<svg xmlns="http://www.w3.org/2000/svg" width="40.099" height="37.822" viewBox="0 0 40.099 37.822">
  <g id="Group_302" data-name="Group 302" transform="translate(-22.184 -18.097)">
    <g id="Path_199" data-name="Path 199" transform="translate(37.163 35.097)" fill="none">
      <path d="M12.56-17S25.119-1.672,25.119,5.265A12.56,12.56,0,1,1,0,5.265C0-1.672,12.56-17,12.56-17Z" stroke="none"/>
      <path d="M 12.55960750579834 -13.76848983764648 C 11.36760807037354 -12.2193078994751 9.638681411743164 -9.897469520568848 7.925437927246094 -7.331647872924805 C 2.769807815551758 0.3896221220493317 1.999998092651367 3.874772071838379 1.999998092651367 5.265012264251709 C 1.999998092651367 11.08768177032471 6.737016677856445 15.82476234436035 12.55960750579834 15.82476234436035 C 18.38219833374023 15.82476234436035 23.11921691894531 11.08768177032471 23.11921691894531 5.265012264251709 C 23.11921691894531 3.874772071838379 22.34940719604492 0.3896221220493317 17.19377708435059 -7.331647872924805 C 15.48053359985352 -9.897469520568848 13.75160694122314 -12.2193078994751 12.55960750579834 -13.76848983764648 M 12.55960750579834 -16.99999809265137 C 12.55960750579834 -16.99999809265137 25.11921691894531 -1.671547889709473 25.11921691894531 5.265012264251709 C 25.11921691894531 12.20157241821289 19.4960880279541 17.82476234436035 12.55960750579834 17.82476234436035 C 5.623126983642578 17.82476234436035 -1.9073486328125e-06 12.20157241821289 -1.9073486328125e-06 5.265012264251709 C -1.9073486328125e-06 -1.671547889709473 12.55960750579834 -16.99999809265137 12.55960750579834 -16.99999809265137 Z" stroke="none" fill="#fff"/>
    </g>
    <path id="Path_201" data-name="Path 201" d="M9057.33,126.239h-21.68v32.435h19.259v-5.068" transform="translate(-9010.34 -103.755)" fill="none" stroke="#fff" stroke-width="2"/>
    <path id="Path_202" data-name="Path 202" d="M9027.514,138.988h15.979" transform="translate(-9004.329 -106.203)" fill="none" stroke="#fff" stroke-linecap="round" stroke-width="2"/>
    <path id="Path_203" data-name="Path 203" d="M9024.184,154.724h15.979" transform="translate(-9001 -110.331)" fill="none" stroke="#fff" stroke-linecap="round" stroke-width="2"/>
  </g>
</svg>
`;
  export const FinancialGrey13 = () : string => `<svg xmlns="http://www.w3.org/2000/svg" width="12.78" height="12.78" viewBox="0 0 12.78 12.78">
  <g id="Group_311" data-name="Group 311" transform="translate(-358.86 -30.86)">
    <line id="Line_28" data-name="Line 28" x2="10.658" y2="10.658" transform="translate(359.921 31.921)" fill="none" stroke="#fff" stroke-linecap="round" stroke-width="1.5"/>
    <line id="Line_29" data-name="Line 29" x1="10.658" y2="10.658" transform="translate(359.921 31.921)" fill="none" stroke="#fff" stroke-linecap="round" stroke-width="1.5"/>
  </g>
</svg>
`;
  export const FinancialGrey14 = () : string => `<svg xmlns="http://www.w3.org/2000/svg" width="27.933" height="20.537" viewBox="0 0 27.933 20.537">
  <g id="Group_318" data-name="Group 318" transform="translate(-43.659 -158.232)">
    <g id="Path_229" data-name="Path 229" transform="translate(45.659 156.232)" fill="none">
      <path d="M11.967,2c9.748,0,13.967,10.268,13.967,10.268S21.705,22.537,11.967,22.537-2,12.268-2,12.268,2.218,2,11.967,2Z" stroke="none"/>
      <path d="M 11.96671676635742 3.499996185302734 C 8.399386405944824 3.499996185302734 5.217666625976562 5.034906387329102 2.509946823120117 8.062095642089844 C 1.023658752441406 9.723738670349121 0.08237838745117188 11.41322040557861 -0.3445568084716797 12.26768589019775 C 0.08369255065917969 13.12340641021729 1.026348114013672 14.81273651123047 2.513206481933594 16.47419738769531 C 5.222507476806641 19.50166702270508 8.40312671661377 21.03671646118164 11.96671676635742 21.03671646118164 C 15.53030681610107 21.03671646118164 18.7109260559082 19.50166702270508 21.42022705078125 16.47419738769531 C 22.9075984954834 14.81216239929199 23.85033226013184 13.12235832214355 24.27799224853516 12.26784515380859 C 23.85046577453613 11.41217231750488 22.90926170349121 9.723165512084961 21.42348670959473 8.062095642089844 C 18.71576690673828 5.034906387329102 15.53404712677002 3.499996185302734 11.96671676635742 3.499996185302734 M 11.96671676635742 1.999996185302734 C 21.7149772644043 1.999996185302734 25.93343734741211 12.26835632324219 25.93343734741211 12.26835632324219 C 25.93343734741211 12.26835632324219 21.70537757873535 22.53671646118164 11.96671676635742 22.53671646118164 C 2.228055953979492 22.53671646118164 -2.000003814697266 12.26835632324219 -2.000003814697266 12.26835632324219 C -2.000003814697266 12.26835632324219 2.218456268310547 1.999996185302734 11.96671676635742 1.999996185302734 Z" stroke="none" fill="#fff"/>
    </g>
    <path id="Path_33966" d="M0,4.778,2.867,1.052l3.27,2.569L8.943,0" transform="translate(53.347 166.384)" fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="1.5"/>
  </g>
</svg>
`;
  export const FinancialGrey15 = () : string => `<svg id="Iconly_Light_Graph" data-name="Iconly/Light/Graph" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
  <g id="Graph" transform="translate(2 2)">
    <path id="Path_33948" d="M8.7,6.975A8.311,8.311,0,0,0,.741,0,.714.714,0,0,0,0,.687H0V.751L.449,7.461a.824.824,0,0,0,.87.769l6.728-.449A.714.714,0,0,0,8.7,7.012Z" transform="translate(10.819 0.777)" fill="none" stroke="#f44040" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="1.5"/>
    <path id="Path_33949" d="M6.145.024A.915.915,0,0,1,7.189.545a.824.824,0,0,1,.082.3c.092,1.3.284,4.146.394,5.684a1.043,1.043,0,0,0,1.117.97h0l5.648-.348a.915.915,0,0,1,.97.915h0A7.7,7.7,0,0,1,.974,11.264a7.323,7.323,0,0,1-.915-2.8A4.723,4.723,0,0,1,0,7.548,7.707,7.707,0,0,1,6.136.024" transform="translate(0.756 4.745)" fill="none" stroke="#f44040" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="1.5"/>
  </g>
</svg>
`;
  export const FinancialGrey16 = () : string => `<svg xmlns="http://www.w3.org/2000/svg" width="11.369" height="16.241" viewBox="0 0 11.369 16.241">
  <path id="lightbulb" d="M10.684,2A5.682,5.682,0,0,0,7.436,12.345v1.835a.812.812,0,0,0,.812.812H13.12a.812.812,0,0,0,.812-.812V12.345A5.682,5.682,0,0,0,10.684,2M8.248,17.429a.812.812,0,0,0,.812.812h3.248a.812.812,0,0,0,.812-.812v-.812H8.248Z" transform="translate(-5 -2)" fill="#e0cbff"/>
</svg>
`;
  export const FinancialGrey17 = () : string => `<svg xmlns="http://www.w3.org/2000/svg" width="14.271" height="8.692" viewBox="0 0 14.271 8.692">
  <path id="Path_12" data-name="Path 12" d="M1971,378l4.742-4.547,5.293,4.547" transform="translate(-1968.879 -371.429)" fill="none" stroke="#fff" stroke-linecap="round" stroke-width="3"/>
</svg>
`;
  export const FinancialGrey18 = () : string => `<svg xmlns="http://www.w3.org/2000/svg" width="14.271" height="8.692" viewBox="0 0 14.271 8.692">
  <path id="Path_12" data-name="Path 12" d="M1971,373.454l4.742,4.547,5.293-4.547" transform="translate(-1968.879 -371.333)" fill="none" stroke="#fff" stroke-linecap="round" stroke-width="3"/>
</svg>
`;
  export const FinancialGrey19 = () : string => `<svg id="share-24px" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
  <path id="Path_34" data-name="Path 34" d="M0,0H24V24H0Z" fill="none"/>
  <path id="Path_35" data-name="Path 35" d="M18,16.08a2.912,2.912,0,0,0-1.96.77L8.91,12.7A3.274,3.274,0,0,0,9,12a3.274,3.274,0,0,0-.09-.7l7.05-4.11A2.993,2.993,0,1,0,15,5a3.274,3.274,0,0,0,.09.7L8.04,9.81a3,3,0,1,0,0,4.38l7.12,4.16a2.821,2.821,0,0,0-.08.65A2.92,2.92,0,1,0,18,16.08Z" fill="#fff"/>
</svg>
`;
  export const FinancialGrey2 = () : string => `<svg xmlns="http://www.w3.org/2000/svg" width="16.5" height="14.17" viewBox="0 0 16.5 14.17">
  <g id="Arrow_-_Left" data-name="Arrow - Left" transform="translate(16.5 0.311) rotate(90)">
    <path id="Stroke_1" data-name="Stroke 1" d="M.5,15V0" transform="translate(6.274 0.75)" fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="1.5"/>
    <path id="Stroke_3" data-name="Stroke 3" d="M12.049,0,6.025,6.05,0,0" transform="translate(0.75 9.7)" fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="1.5"/>
  </g>
</svg>
`;
  export const FinancialGrey20 = () : string => `<svg id="Group_7" data-name="Group 7" xmlns="http://www.w3.org/2000/svg" width="24.718" height="18.164" viewBox="0 0 24.718 18.164">
  <path id="Path_2" data-name="Path 2" d="M242,32.581a5.515,5.515,0,0,1-3.261,4.993c-.192.1-.392.187-.592.273-.744.317-.746.317-1.324-.264a2.926,2.926,0,0,1-.943-2.5c.029-.25.1-.4.415-.428a8.77,8.77,0,0,0,2.909-.718,2.909,2.909,0,0,0,1.681-1.727,1.843,1.843,0,0,1,.256-.551.577.577,0,0,1,.418-.228.518.518,0,0,1,.348.321A4.782,4.782,0,0,1,242,32.581Z" transform="translate(-217.278 -31.432)" fill="#15182c"/>
  <path id="Path_3" data-name="Path 3" d="M195.365,35.643a3.206,3.206,0,0,1-1.459,2.37.318.318,0,0,1-.256.045c-2.08-.733-3.715-1.946-4.259-4.207a7.914,7.914,0,0,1-.093-1.981.609.609,0,0,1,.379-.43.544.544,0,0,1,.441.3c.565,1.9,2.112,2.447,3.809,2.79.226.046.456.073.685.1C195.315,34.7,195.364,34.752,195.365,35.643Z" transform="translate(-189.28 -31.435)" fill="#15182c"/>
  <path id="Path_4" data-name="Path 4" d="M214.31,39.013a4.264,4.264,0,0,1-1.359-2.447,13.119,13.119,0,0,1-.012-1.673,26.131,26.131,0,0,1-5.235-2.634,24.381,24.381,0,0,1-5.014,2.678.856.856,0,0,0-.023.185,4.162,4.162,0,0,1-1.424,3.987c-.566.544-1.09,1.132-1.628,1.695.721.94,1.615.961,2.93.084.054.092.115.179.16.274.562,1.206,1.115,2.416,1.686,3.617a.435.435,0,0,1-.058.538,1.87,1.87,0,0,0-.276.507,2.641,2.641,0,0,0,1.169,3.139l1.229.742a2.693,2.693,0,0,0,2.749.021l1.21-.705a2.649,2.649,0,0,0,1.309-2.723,2.267,2.267,0,0,0-.408-.987.443.443,0,0,1-.051-.542c.575-1.214,1.138-2.435,1.707-3.652a1.875,1.875,0,0,1,.147-.225c1.27.877,2.257.847,2.913-.1C215.46,40.2,214.895,39.6,214.31,39.013Zm-10.489,1.6c-.138-.457-.052-.584.422-.623.081-.007.162,0,.244,0,1,.006,1.532.585,1.4,1.5-.032.224-.115.331-.357.337A1.829,1.829,0,0,1,203.821,40.61Zm2.033,6.629a.57.57,0,0,1-.541-.592.541.541,0,0,1,.588-.535.517.517,0,0,1,.514.562A.554.554,0,0,1,205.854,47.239Zm3.929,0a.569.569,0,0,1-.552-.542.558.558,0,0,1,.538-.591.55.55,0,0,1,.566.558A.557.557,0,0,1,209.783,47.239Zm.272-5.436a.416.416,0,0,1-.271-.267A1.2,1.2,0,0,1,210.87,40a8.689,8.689,0,0,1,.974-.006A1.677,1.677,0,0,1,210.054,41.8Z" transform="translate(-195.493 -31.929)" fill="#15182c"/>
</svg>
`;
  export const FinancialGrey21 = () : string => `<svg xmlns="http://www.w3.org/2000/svg" width="26.5" height="26.5" viewBox="0 0 26.5 26.5">
  <g id="Chart" transform="translate(0.75 0.75)">
    <path id="Line_182" d="M.476,0V8.575" transform="translate(6.238 10.252)" fill="none" stroke="#b7bad1" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="1.5"/>
    <path id="Line_183" d="M.476,0V12.678" transform="translate(12.071 6.149)" fill="none" stroke="#b7bad1" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="1.5"/>
    <path id="Line_184" d="M.476,0V4.044" transform="translate(17.81 14.784)" fill="none" stroke="#b7bad1" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="1.5"/>
    <path id="Path" d="M18.357,0H6.643C2.56,0,0,2.89,0,6.981V18.019C0,22.11,2.548,25,6.643,25H18.357C22.452,25,25,22.11,25,18.019V6.981C25,2.89,22.452,0,18.357,0Z" fill="none" stroke="#b7bad1" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="1.5"/>
  </g>
</svg>
`;
  export const FinancialGrey22 = () : string => `<svg id="Iconly_Light_Message" data-name="Iconly/Light/Message" xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 28 28">
  <g id="Message" transform="translate(2.333 4.083)">
    <path id="Path_445" d="M13.2,0,8.223,4.007a2.594,2.594,0,0,1-3.2,0L0,0" transform="translate(4.613 6.488)" fill="none" stroke="#200e32" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="1.5"/>
    <path id="Rectangle_511" d="M5.7,0h11a5.783,5.783,0,0,1,4.177,1.855,5.853,5.853,0,0,1,1.547,4.321v7.616a5.853,5.853,0,0,1-1.547,4.321A5.783,5.783,0,0,1,16.7,19.969H5.7C2.3,19.969,0,17.2,0,13.792V6.176C0,2.771,2.3,0,5.7,0Z" transform="translate(0 0)" fill="none" stroke="#200e32" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="1.5"/>
  </g>
</svg>
`;
  export const FinancialGrey23 = () : string => `<svg xmlns="http://www.w3.org/2000/svg" width="20.271" height="20.791" viewBox="0 0 20.271 20.791">
  <g id="Graph" transform="translate(-0.006 -0.027)">
    <path id="Path_33948" d="M8.7,6.975A8.311,8.311,0,0,0,.741,0,.714.714,0,0,0,0,.687H0V.751L.449,7.461a.824.824,0,0,0,.87.769l6.728-.449A.714.714,0,0,0,8.7,7.012Z" transform="translate(10.819 0.777)" fill="none" stroke="#f44040" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="1.5"/>
    <path id="Path_33949" d="M6.145.024A.915.915,0,0,1,7.189.545a.824.824,0,0,1,.082.3c.092,1.3.284,4.146.394,5.684a1.043,1.043,0,0,0,1.117.97h0l5.648-.348a.915.915,0,0,1,.97.915h0A7.7,7.7,0,0,1,.974,11.264a7.323,7.323,0,0,1-.915-2.8A4.723,4.723,0,0,1,0,7.548,7.707,7.707,0,0,1,6.136.024" transform="translate(0.756 4.745)" fill="none" stroke="#f44040" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="1.5"/>
  </g>
</svg>
`;
  export const FinancialGrey24 = () : string => `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="29.091" viewBox="0 0 32 29.091">
  <path id="Negative" d="M33,14.091a2.908,2.908,0,0,0-2.909-2.909H20.9l1.4-6.647a2.408,2.408,0,0,0,.044-.465,2.19,2.19,0,0,0-.64-1.542L20.156,1l-9.571,9.571a2.9,2.9,0,0,0-.858,2.065V27.182a2.909,2.909,0,0,0,2.909,2.909H25.727A2.889,2.889,0,0,0,28.4,28.316L32.8,18.062A2.874,2.874,0,0,0,33,17V14.091m-32,16H6.818V12.636H1Z" transform="translate(33 30.091) rotate(180)" fill="#f07"/>
</svg>
`;
  export const FinancialGrey25 = () : string => `<svg xmlns="http://www.w3.org/2000/svg" width="29.091" height="32" viewBox="0 0 29.091 32">
  <path id="Nuetral" d="M33,14.091a2.908,2.908,0,0,0-2.909-2.909H20.9l1.4-6.647a2.408,2.408,0,0,0,.044-.465,2.19,2.19,0,0,0-.64-1.542L20.156,1l-9.571,9.571a2.9,2.9,0,0,0-.858,2.065V27.182a2.909,2.909,0,0,0,2.909,2.909H25.727A2.889,2.889,0,0,0,28.4,28.316L32.8,18.062A2.874,2.874,0,0,0,33,17V14.091m-32,16H6.818V12.636H1Z" transform="translate(-1 33) rotate(-90)" fill="#ffc300"/>
</svg>
`;
  export const FinancialGrey26 = () : string => `<svg xmlns="http://www.w3.org/2000/svg" width="32" height="29.091" viewBox="0 0 32 29.091">
  <path id="Positive" d="M33,14.091a2.908,2.908,0,0,0-2.909-2.909H20.9l1.4-6.647a2.408,2.408,0,0,0,.044-.465,2.19,2.19,0,0,0-.64-1.542L20.156,1l-9.571,9.571a2.9,2.9,0,0,0-.858,2.065V27.182a2.909,2.909,0,0,0,2.909,2.909H25.727A2.889,2.889,0,0,0,28.4,28.316L32.8,18.062A2.874,2.874,0,0,0,33,17V14.091m-32,16H6.818V12.636H1Z" transform="translate(-1 -1)" fill="#9853ff"/>
</svg>
`;
  export const FinancialGrey3 = () : string => `<svg id="building-house" xmlns="http://www.w3.org/2000/svg" width="23.381" height="24.35" viewBox="0 0 23.381 24.35">
  <g id="Group_107" data-name="Group 107" transform="translate(0)">
    <path id="Path_184" data-name="Path 184" d="M170.935,269.167h-1.522a.833.833,0,0,0-.83.83v1.383a.833.833,0,0,0,.83.83h1.522a.833.833,0,0,0,.83-.83V270A.833.833,0,0,0,170.935,269.167Z" transform="translate(-160.835 -256.024)" fill="#944efc"/>
    <path id="Path_185" data-name="Path 185" d="M270.794,271.381V270a.833.833,0,0,0-.83-.83H268.58a.833.833,0,0,0-.83.83v1.383a.833.833,0,0,0,.83.83h1.383A.833.833,0,0,0,270.794,271.381Z" transform="translate(-255.16 -256.024)" fill="#944efc"/>
    <path id="Path_186" data-name="Path 186" d="M170.935,175.667h-1.522a.833.833,0,0,0-.83.83v1.384a.833.833,0,0,0,.83.83h1.522a.833.833,0,0,0,.83-.83V176.5A.833.833,0,0,0,170.935,175.667Z" transform="translate(-160.835 -167.089)" fill="#944efc"/>
    <path id="Path_187" data-name="Path 187" d="M268.58,178.711h1.383a.833.833,0,0,0,.83-.83V176.5a.833.833,0,0,0-.83-.83H268.58a.833.833,0,0,0-.83.83v1.383A.833.833,0,0,0,268.58,178.711Z" transform="translate(-255.16 -167.089)" fill="#944efc"/>
    <path id="Path_188" data-name="Path 188" d="M170.935,85h-1.522a.833.833,0,0,0-.83.83v1.383a.833.833,0,0,0,.83.83h1.522a.833.833,0,0,0,.83-.83V85.83A.833.833,0,0,0,170.935,85Z" transform="translate(-160.835 -80.849)" fill="#944efc"/>
    <path id="Path_189" data-name="Path 189" d="M268.58,88.044h1.383a.833.833,0,0,0,.83-.83V85.83a.833.833,0,0,0-.83-.83H268.58a.833.833,0,0,0-.83.83v1.383A.833.833,0,0,0,268.58,88.044Z" transform="translate(-255.16 -80.849)" fill="#944efc"/>
    <path id="Path_190" data-name="Path 190" d="M29.285,4.441V.83a.833.833,0,0,0-.83-.83h-13.7a.833.833,0,0,0-.83.83V4.441l-3.777,3.9a.816.816,0,0,0-.235.581v14.6a.833.833,0,0,0,.83.83h7.609a.82.82,0,0,0,.706-.4.838.838,0,0,0,.4-.706V20.061h4.289v3.182a.847.847,0,0,0,.595.8.814.814,0,0,0,.65.3h7.471a.833.833,0,0,0,.83-.83V8.924a.816.816,0,0,0-.235-.581ZM11.576,9.256l2.352-2.435V22.69H11.576ZM18.632,18.4a.833.833,0,0,0-.83.83V22.69H15.588V1.66H27.625V22.69H25.411V19.231a.833.833,0,0,0-.83-.83H18.632Zm13,4.289H29.285V6.821l2.352,2.435Z" transform="translate(-9.916 0)" fill="#944efc"/>
  </g>
</svg>
`;
  export const FinancialGrey4 = () : string => `<svg xmlns="http://www.w3.org/2000/svg" width="27.833" height="30.703" viewBox="0 0 27.833 30.703">
  <g id="Calendar" transform="translate(1 1)">
    <path id="Line_200" d="M0,.473H25.58" transform="translate(0.133 10.153)" fill="none" stroke="#772ce8" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2"/>
    <path id="Line_201" d="M.459.473H.472" transform="translate(18.833 15.758)" fill="none" stroke="#772ce8" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2"/>
    <path id="Line_202" d="M.459.473H.472" transform="translate(12.464 15.758)" fill="none" stroke="#772ce8" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2"/>
    <path id="Line_203" d="M.459.473H.472" transform="translate(6.083 15.758)" fill="none" stroke="#772ce8" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2"/>
    <path id="Line_204" d="M.459.473H.472" transform="translate(18.833 21.336)" fill="none" stroke="#772ce8" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2"/>
    <path id="Line_205" d="M.459.473H.472" transform="translate(12.464 21.336)" fill="none" stroke="#772ce8" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2"/>
    <path id="Line_206" d="M.459.473H.472" transform="translate(6.083 21.336)" fill="none" stroke="#772ce8" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2"/>
    <path id="Line_207" d="M.463,0V4.723" transform="translate(18.256)" fill="none" stroke="#772ce8" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2"/>
    <path id="Line_208" d="M.463,0V4.723" transform="translate(6.663)" fill="none" stroke="#772ce8" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2"/>
    <path id="Path" d="M19,0H6.847C2.632,0,0,2.348,0,6.663V19.651c0,4.383,2.632,6.786,6.847,6.786H18.985c4.228,0,6.847-2.361,6.847-6.677V6.663C25.846,2.348,23.227,0,19,0Z" transform="translate(0 2.266)" fill="none" stroke="#772ce8" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2"/>
  </g>
</svg>
`;
  export const FinancialGrey5 = () : string => `<svg xmlns="http://www.w3.org/2000/svg" width="25.424" height="25.505" viewBox="0 0 25.424 25.505">
  <g id="Iconly_Light_Activity" data-name="Iconly/Light/Activity" transform="translate(0.75 0.75)">
    <g id="Activity">
      <path id="Path_33966" d="M0,6.236,3.741,1.373,8.009,4.725,11.67,0" transform="translate(5.584 9.394)" fill="none" stroke="#b7bad1" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="1.5"/>
      <circle id="Ellipse_741" cx="2.403" cy="2.403" r="2.403" transform="translate(19.119)" fill="none" stroke="#b7bad1" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="1.5"/>
      <path id="Path" d="M15.183,0H6.1C2.334,0,0,2.666,0,6.43v10.1c0,3.764,2.288,6.419,6.1,6.419H16.854c3.764,0,6.1-2.654,6.1-6.419v-8.8" transform="translate(0 1.053)" fill="none" stroke="#b7bad1" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="1.5"/>
    </g>
  </g>
</svg>
`;
  export const FinancialGrey6 = () : string => `<svg id="Iconly_Light_Search" data-name="Iconly/Light/Search" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
  <g id="Search" transform="translate(2 2)">
    <circle id="Ellipse_739" cx="8.989" cy="8.989" r="8.989" transform="translate(0.778 0.778)" fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="1.5"/>
    <path id="Line_181" d="M0,0,3.524,3.515" transform="translate(16.018 16.485)" fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="1.5"/>
  </g>
</svg>
`;
  export const FinancialGrey7 = () : string => `<svg xmlns="http://www.w3.org/2000/svg" width="20.555" height="25.121" viewBox="0 0 20.555 25.121">
  <path id="Path_9" data-name="Path 9" d="M22.1,13.887a11.579,11.579,0,0,0-1.04-1.108c-.9-.81-1.932-1.391-2.8-2.242a6.656,6.656,0,0,1-1.8-5.812.974.974,0,0,0-1.422-1.052,11.54,11.54,0,0,0-1.312.921A10.664,10.664,0,0,0,10.5,16.615a1.139,1.139,0,0,1,.108.446.749.749,0,0,1-.473.675.837.837,0,0,1-.891-.162.783.783,0,0,1-.189-.23A6.6,6.6,0,0,1,7.71,12.793a.627.627,0,0,0-1.139-.407A9.938,9.938,0,0,0,5,18.3,9.757,9.757,0,0,0,5.4,20.33a9.062,9.062,0,0,0,.959,2.337,9.451,9.451,0,0,0,6.7,4.349,10.211,10.211,0,0,0,8.2-2.161A8,8,0,0,0,23.32,15.94l-.176-.351a15.145,15.145,0,0,0-1.04-1.7" transform="translate(-4.235 -2.765)" fill="none" stroke="#b7bad1" stroke-miterlimit="10" stroke-width="1.5"/>
</svg>
`;
  export const FinancialGrey8 = () : string => `<svg xmlns="http://www.w3.org/2000/svg" width="17.933" height="11.902" viewBox="0 0 17.933 11.902">
  <g id="Group_81" data-name="Group 81" transform="translate(0.753 0.802)">
    <path id="Path_16" data-name="Path 16" d="M0,0,6.3,5.915,9.115,3.1l6.043,6.043" transform="translate(0 0)" fill="none" stroke="#f44040" stroke-width="2.2"/>
    <path id="Path_17" data-name="Path 17" d="M0,4.479H4.164V0" transform="translate(11.916 5.521)" fill="none" stroke="#f44040" stroke-width="2.2"/>
  </g>
</svg>
`;
  export const FinancialGrey9 = () : string => `<svg xmlns="http://www.w3.org/2000/svg" width="28.263" height="28.263" viewBox="0 0 28.263 28.263">
  <g id="Group_125" data-name="Group 125" transform="translate(-39.352 -2841.964)">
    <path id="Path_41" data-name="Path 41" d="M11.425,22.849A11.425,11.425,0,1,0,0,11.425,11.434,11.434,0,0,0,11.425,22.849Zm0-21.293a9.869,9.869,0,1,1-9.869,9.869A9.873,9.873,0,0,1,11.425,1.556Z" transform="translate(39.352 2848.262) rotate(-16)" fill="#944efc"/>
    <path id="Path_42" data-name="Path 42" d="M0,1.453s6.2-3.27,20.135,0" transform="translate(42.431 2854.149) rotate(-16)" fill="none" stroke="#944efc" stroke-width="1.5"/>
    <path id="Path_43" data-name="Path 43" d="M0,0S6.2,3.27,20.135,0" transform="translate(44.403 2861.026) rotate(-16)" fill="none" stroke="#944efc" stroke-width="1.5"/>
    <g id="Group_124" data-name="Group 124" transform="translate(54.797 2845.133) rotate(74)">
      <path id="Path_195" data-name="Path 195" d="M0,1.453s6.355-3.27,20.652,0" transform="translate(0 0)" fill="none" stroke="#944efc" stroke-width="1.5"/>
      <path id="Path_196" data-name="Path 196" d="M0,0S6.355,3.27,20.652,0" transform="translate(0 7.155)" fill="none" stroke="#944efc" stroke-width="1.5"/>
    </g>
  </g>
</svg>
`;
  