/**
 * Generated by scripts/generate-icons.js
 * DO NOT EDIT!
 */

export const WatsonGrey1 = () : string => `<svg width="25" height="24" viewBox="0 0 25 24" xmlns="http://www.w3.org/2000/svg" fill='none'>
<path d="M2.00049 4H4.14747C4.37866 4 4.57971 4.1585 4.63366 4.38331L7.7532 17.3814C7.80715 17.6062 8.0082 17.7647 8.23939 17.7647H18.4036C18.6424 17.7647 18.8479 17.5958 18.8941 17.3614L20.9416 6.97909C21.0026 6.67007 20.7661 6.38235 20.4511 6.38235H5.85461" stroke-width="1.5" stroke-linecap="round" />
<circle cx="9.60352" cy="21.1328" r="1.25" />
<circle cx="16.6035" cy="21.1328" r="1.25" />
</svg>
`;
  export const WatsonGrey10 = () : string => `<svg width="20" height="19" viewBox="0 0 20 19" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M1 3V16.7676C1 17.1499 1.41156 17.3908 1.74486 17.2036L4.54967 15.6281C4.69923 15.5441 4.86787 15.5 5.0394 15.5H17C18.1046 15.5 19 14.6046 19 13.5V3C19 1.89543 18.1046 1 17 1H3C1.89543 1 1 1.89543 1 3Z" stroke-width="1.5"/>
<path d="M6.5 10.5H13.5" stroke-width="1.5" stroke-linecap="round"/>
<path d="M6.5 5.5H10.5" stroke-width="1.5" stroke-linecap="round"/>
</svg>
`;
  export const WatsonGrey11 = () : string => `<svg width="19" height="17" viewBox="0 0 19 17" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M3.01338 3.37006H4.85864C5.19492 3.37006 5.50869 3.20104 5.6937 2.92021L6.6624 1.44985C6.84741 1.16903 7.16117 1 7.49746 1H11.1463C11.4857 1 11.802 1.17218 11.9862 1.45727L12.8132 2.73711C12.9974 3.02221 13.3137 3.19439 13.6531 3.19439H16.0134C17.1189 3.19439 18.0148 4.09133 18.0134 5.19687L18.0025 14.0025C18.0011 15.1061 17.1061 16 16.0025 16H3.00252C1.89697 16 1.00113 15.103 1.00252 13.9975L1.01338 5.36755C1.01477 4.26396 1.90979 3.37006 3.01338 3.37006Z" stroke-width="1.3"/>
<circle cx="9.50781" cy="9.30859" r="3" stroke-width="1.3"/>
</svg>
`;
  export const WatsonGrey12 = () : string => `<svg width="9" height="16" viewBox="0 0 9 16" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M8 15L1 8L8 1" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
`;
  export const WatsonGrey13 = () : string => `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M11.9 20.8C16.8153 20.8 20.8 16.8153 20.8 11.9C20.8 6.98467 16.8153 3 11.9 3C6.98467 3 3 6.98467 3 11.9C3 16.8153 6.98467 20.8 11.9 20.8Z" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M11.8998 8.60039C12.5073 8.60039 12.9998 8.1079 12.9998 7.50039C12.9998 6.89288 12.5073 6.40039 11.8998 6.40039C11.2923 6.40039 10.7998 6.89288 10.7998 7.50039C10.7998 8.1079 11.2923 8.60039 11.8998 8.60039Z" />
<path d="M11.3999 10.5H11.8999V16.1008H12.6999" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
`;
  export const WatsonGrey14 = () : string => `<svg width="375" height="248" viewBox="0 0 375 248" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle opacity="0.15" cx="324" cy="73" r="101" stroke="url(#paint0_linear)" stroke-width="40"/>
<circle opacity="0.15" r="64.5" transform="matrix(-1 0 0 1 26.5 168.5)" stroke="url(#paint1_linear)" stroke-width="30"/>
<circle opacity="0.2" r="60.3678" transform="matrix(-0.574499 0.818505 0.818505 0.574499 324 72.9999)" stroke="url(#paint2_linear)"/>
<circle opacity="0.2" cx="26.8546" cy="168.782" r="36.9278" transform="rotate(54.9354 26.8546 168.782)" stroke="url(#paint3_linear)"/>
<defs>
<linearGradient id="paint0_linear" x1="324" y1="-28" x2="324" y2="174" gradientUnits="userSpaceOnUse">
<stop stop-color="white"/>
<stop offset="1" stop-color="white" stop-opacity="0"/>
</linearGradient>
<linearGradient id="paint1_linear" x1="64.5" y1="0" x2="64.5" y2="129" gradientUnits="userSpaceOnUse">
<stop stop-color="white"/>
<stop offset="1" stop-color="white" stop-opacity="0"/>
</linearGradient>
<linearGradient id="paint2_linear" x1="60.3678" y1="0" x2="60.3678" y2="120.736" gradientUnits="userSpaceOnUse">
<stop stop-color="white"/>
<stop offset="1" stop-color="white" stop-opacity="0"/>
</linearGradient>
<linearGradient id="paint3_linear" x1="26.8546" y1="131.855" x2="26.8546" y2="205.71" gradientUnits="userSpaceOnUse">
<stop stop-color="white"/>
<stop offset="1" stop-color="white" stop-opacity="0"/>
</linearGradient>
</defs>
</svg>
`;
  export const WatsonGrey15 = () : string => `<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M8.38213 6.79576C10.0322 6.79576 11.3699 5.45811 11.3699 3.80804C11.3699 2.15796 10.0322 0.820312 8.38213 0.820312C6.73206 0.820312 5.39441 2.15796 5.39441 3.80804C5.39441 5.45811 6.73206 6.79576 8.38213 6.79576Z" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M0.797852 17.3686C0.797852 13.1169 4.24522 9.78442 8.38207 9.78442C10.2207 9.78442 11.9444 10.4739 13.2084 11.5081" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M14.4726 18.5177L12.2892 18.9773C11.9445 19.0922 11.5998 18.7475 11.7147 18.4028L12.1743 16.2194C12.1743 15.9896 12.2892 15.8747 12.4042 15.7598L16.541 11.6229C16.8857 11.2782 17.5752 11.2782 17.92 11.6229L19.0691 12.7721C19.4138 13.1168 19.4138 13.8063 19.0691 14.151L14.9322 18.2879C14.8173 18.4028 14.7024 18.4028 14.4726 18.5177Z" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
`;
  export const WatsonGrey16 = () : string => `<svg width="21" height="18" viewBox="0 0 21 18" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M6 1V3" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M6 7L6 11" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M6 15V17" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M17.9146 9.06471C17.9146 7.66437 18.8415 6.49741 20 6.14732V2.64646C20 1.7129 19.3049 1.01272 18.378 1.01272H2.62195C1.69512 0.896029 1 1.5962 1 2.52977V6.03063C2.27439 6.49741 3.08537 7.54767 3.08537 8.94802C3.08537 10.3484 2.15854 11.5153 1 11.8654V15.3663C1 16.2998 1.69512 17 2.62195 17H18.378C19.3049 17 20 16.2998 20 15.3663V11.8654C18.7256 11.5153 17.9146 10.3484 17.9146 9.06471Z" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
`;
  export const WatsonGrey17 = () : string => `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M21.1211 8.9499H2.27063L4.00401 5.0498C4.22068 4.61645 4.54569 4.39978 4.97903 4.39978H18.4127C18.8461 4.39978 19.2794 4.61645 19.3877 5.0498L21.1211 8.9499Z" stroke-width="1.2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M2.27063 8.95007V9.70843C2.27063 11.0085 3.35399 12.0918 4.65402 12.0918C5.95406 11.9835 7.03742 10.9001 7.03742 9.60009V8.95007" stroke-width="1.2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M7.03735 8.95007V9.70843C7.03735 11.0085 8.12071 12.0918 9.42075 12.0918C10.7208 12.0918 11.8041 11.0085 11.8041 9.70843V8.95007" stroke-width="1.2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M7.03735 8.95007V9.70843C7.03735 11.0085 8.12071 12.0918 9.42075 12.0918C10.7208 12.0918 11.8041 11.0085 11.8041 9.70843V8.95007" stroke-width="1.2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M11.6962 8.95007V9.70843C11.6962 11.0085 12.7795 12.0918 14.0796 12.0918C15.3796 12.0918 16.463 11.0085 16.463 9.70843V8.95007" stroke-width="1.2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M11.6962 8.95007V9.70843C11.6962 11.0085 12.7795 12.0918 14.0796 12.0918C15.3796 12.0918 16.463 11.0085 16.463 9.70843V8.95007" stroke-width="1.2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M16.4629 8.95007V9.70843C16.4629 11.0085 17.5463 12.0918 18.8463 12.0918C20.1463 12.0918 21.2297 11.0085 21.2297 9.70843V8.95007" stroke-width="1.2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M3.57092 11.7665V18.9167C3.57092 19.5667 4.00427 20 4.65428 20H18.8463C19.4963 20 19.9297 19.5667 19.9297 18.9167V11.7665" stroke-width="1.2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M9.42151 15.6663L11.0466 17.2913L14.08 14.2579" stroke-width="1.2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
`;
  export const WatsonGrey18 = () : string => `<svg width="25" height="20" viewBox="0 0 25 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M23.8251 4.65197L14.043 8.17351L4.26099 4.65197L14.043 1L23.8251 4.65197Z" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M7.52137 8.43571L1 6.08801" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M5.56533 11.3046L1.26123 9.60901" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M4.26123 4.65308V15.3481L14.0433 19.0001L23.8253 15.3481V4.65308" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M14.043 18.9994V8.17395" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
`;
  export const WatsonGrey19 = () : string => `<svg width="24" height="23" viewBox="0 0 24 23" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M23 5.2L12 9.25L1 5.2L12 1L23 5.2Z" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M1 5.125V17.425L12 21.625L23 17.425V5.125" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M12 21.625V9.25" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M8.5625 2.375L18.875 6.575V10.625" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
`;
  export const WatsonGrey2 = () : string => `<svg width="25" height="24" viewBox="0 0 25 24" xmlns="http://www.w3.org/2000/svg" fill='none'>
<path d="M4.94118 13.371V20.5C4.94118 20.7761 5.16503 21 5.44118 21H9.5C9.77614 21 10 20.7761 10 20.5V16.6935C10 16.4174 10.2239 16.1935 10.5 16.1935H13.5C13.7761 16.1935 14 16.4174 14 16.6935V20.5C14 20.7761 14.2239 21 14.5 21H18.5588C18.835 21 19.0588 20.7761 19.0588 20.5V13.371C19.0588 13.0948 19.2827 12.871 19.5588 12.871H20.7817C21.2287 12.871 21.4511 12.3292 21.133 12.0151L12.3513 3.34672C12.1565 3.15451 11.8435 3.15451 11.6487 3.34672L2.86703 12.0151C2.54889 12.3292 2.77126 12.871 3.21828 12.871H4.44118C4.71732 12.871 4.94118 13.0948 4.94118 13.371Z" stroke-width="1.5" />
</svg>
`;
  export const WatsonGrey20 = () : string => `<svg width="23" height="21" viewBox="0 0 23 21" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M19.8863 4.9875L10.5645 8.53125L1.24268 4.9875L10.5645 1.3125L19.8863 4.9875Z" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M19.8867 13.389V4.98901" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M1.24268 4.98901V15.7515L10.5645 19.4265L13.9204 18.114" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M10.5649 19.425V8.53125" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M16.0342 16.5378L18.1471 18.7691L22.0001 14.7003" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
`;
  export const WatsonGrey21 = () : string => `<svg width="26" height="24" viewBox="0 0 26 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M21.8075 6.24619L12.9408 9.37645M21.8075 6.24619L12.9408 3L4.19226 6.24619M21.8075 6.24619L25 9.72516L16.1333 12.9714L12.9408 9.37645M12.9408 9.37645L4.19226 6.24619M12.9408 9.37645V21M12.9408 9.37645L9.86674 12.9714L1 9.72516L4.19226 6.24619M4.19226 10.8845V17.7538L12.9408 21M12.9408 21L21.8075 17.7538V11.0005" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
`;
  export const WatsonGrey22 = () : string => `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M11.9 20.8C16.8153 20.8 20.8 16.8153 20.8 11.9C20.8 6.98467 16.8153 3 11.9 3C6.98467 3 3 6.98467 3 11.9C3 16.8153 6.98467 20.8 11.9 20.8Z" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M11.8998 17.2C12.5073 17.2 12.9998 16.7075 12.9998 16.1C12.9998 15.4925 12.5073 15 11.8998 15C11.2923 15 10.7998 15.4925 10.7998 16.1C10.7998 16.7075 11.2923 17.2 11.8998 17.2Z"/>
<path d="M9.69971 8.50059C9.99971 7.70059 10.7997 7.10059 11.7997 7.10059C12.9997 7.10059 14.0997 8.10059 14.0997 9.40059C14.0997 11.5006 11.7997 11.8006 11.7997 12.6006V13.2006" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
`;
  export const WatsonGrey23 = () : string => `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M12 15C14.2091 15 16 13.2091 16 11C16 8.79086 14.2091 7 12 7C9.79086 7 8 8.79086 8 11C8 13.2091 9.79086 15 12 15Z" stroke-width="1.2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M14 11C14 12.1111 13.1111 13 12 13C10.8889 13 10 12.1111 10 11" stroke-width="1.2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M18.8824 4H5.11765C3.95294 4 3 4.95031 3 6.1118V16.1429C3 17.3043 3.95294 18.2547 5.11765 18.2547H9.24706L12 21L14.7529 18.2547H18.8824C20.0471 18.2547 21 17.3043 21 16.1429V6.1118C21 4.95031 20.0471 4 18.8824 4Z" stroke-width="1.2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
`;
  export const WatsonGrey24 = () : string => `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M3 4V19H21" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M7 14.3562L9.35897 12.9315L11 16L13.7692 9.42466L19 8" stroke-width="1.3" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
`;
  export const WatsonGrey25 = () : string => `<svg width="8" height="14" viewBox="0 0 8 14" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M1 1L7 7L1 13" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
`;
  export const WatsonGrey3 = () : string => `<svg width="25" height="24" viewBox="0 0 25 24" xmlns="http://www.w3.org/2000/svg" fill='none'>
<path d="M12.8419 20.6806C12.6493 20.8603 12.3503 20.8597 12.1584 20.6793L11.122 19.7052C6.22951 15.1243 2.99951 12.103 2.99951 8.3951C2.99951 5.37384 5.29851 3 8.22451 3C9.67221 3 11.0689 3.60944 12.0891 4.60427C12.3142 4.82372 12.6849 4.82372 12.9099 4.60427C13.9301 3.60944 15.3268 3 16.7745 3C19.7005 3 21.9995 5.37384 21.9995 8.3951C21.9995 12.103 18.7695 15.1243 13.877 19.715L12.8419 20.6806Z" stroke-width="1.5"/>
</svg>
`;
  export const WatsonGrey4 = () : string => `<svg width="25" height="24" viewBox="0 0 25 24" xmlns="http://www.w3.org/2000/svg" fill='none'>
<path d="M18.0475 5H5.97046C5.71381 5 5.49885 5.1943 5.473 5.44964L4.05572 19.4496C4.0259 19.7442 4.25712 20 4.55317 20H19.4475C19.7433 20 19.9745 19.7446 19.945 19.4502L18.545 5.45025C18.5195 5.19465 18.3044 5 18.0475 5Z" stroke-width="1.5" />
<path d="M8.5 5.5V6C8.5 7.933 10.067 9.5 12 9.5V9.5C13.933 9.5 15.5 7.933 15.5 6V5.5" stroke-width="1.5"/>
</svg>
`;
  export const WatsonGrey5 = () : string => `<svg width="25" height="24" viewBox="0 0 25 24" xmlns="http://www.w3.org/2000/svg" fill='none'>
<path fill-rule="evenodd" clip-rule="evenodd" d="M11.9995 4.75C10.7569 4.75 9.74951 5.75736 9.74951 7C9.74951 8.24264 10.7569 9.25 11.9995 9.25C13.2422 9.25 14.2495 8.24264 14.2495 7C14.2495 5.75736 13.2422 4.75 11.9995 4.75ZM8.24951 7C8.24951 4.92893 9.92844 3.25 11.9995 3.25C14.0706 3.25 15.7495 4.92893 15.7495 7C15.7495 9.07107 14.0706 10.75 11.9995 10.75C9.92844 10.75 8.24951 9.07107 8.24951 7Z" />
<path fill-rule="evenodd" clip-rule="evenodd" d="M3.24951 20.8298C3.24951 16.0913 7.09081 12.25 11.8293 12.25H12.1697C16.9082 12.25 20.7495 16.0913 20.7495 20.8298C20.7495 21.338 20.3375 21.75 19.8293 21.75H4.16972C3.6615 21.75 3.24951 21.338 3.24951 20.8298ZM4.77291 20.25H19.2261C18.9312 16.6111 15.8846 13.75 12.1697 13.75H11.8293C8.11445 13.75 5.06785 16.6111 4.77291 20.25Z" />
</svg>
`;
  export const WatsonGrey6 = () : string => `<svg width="18" height="20" viewBox="0 0 18 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M1 15.3317C0.585786 15.3317 0.25 15.6674 0.25 16.0817C0.25 16.4959 0.585786 16.8317 1 16.8317V15.3317ZM17 16.8317C17.4142 16.8317 17.75 16.4959 17.75 16.0817C17.75 15.6674 17.4142 15.3317 17 15.3317V16.8317ZM2.63265 16.0817H1.88265V16.8317H2.63265V16.0817ZM7.24811 2.17037L6.68928 1.67016L6.68928 1.67016L7.24811 2.17037ZM7.91317 1.42738L7.35434 0.927167V0.927167L7.91317 1.42738ZM9.7603 1.42738L9.20148 1.92759V1.92759L9.7603 1.42738ZM10.4222 2.16686L10.981 1.66665V1.66665L10.4222 2.16686ZM15.3673 16.0817V16.8317H16.1173V16.0817H15.3673ZM6.12755 16.4465V16.8112H7.62755V16.4465H6.12755ZM11.5459 16.8112V16.4465H10.0459V16.8112H11.5459ZM8.83673 19.75C10.409 19.75 11.5459 18.354 11.5459 16.8112H10.0459C10.0459 17.6862 9.42856 18.25 8.83673 18.25V19.75ZM6.12755 16.8112C6.12755 18.354 7.2645 19.75 8.83673 19.75V18.25C8.24491 18.25 7.62755 17.6862 7.62755 16.8112H6.12755ZM1 16.8317H17V15.3317H1V16.8317ZM3.38265 16.0817V7.25709H1.88265V16.0817H3.38265ZM7.80693 2.67059L8.47199 1.92759L7.35434 0.927167L6.68928 1.67016L7.80693 2.67059ZM9.20148 1.92759L9.86339 2.66707L10.981 1.66665L10.3191 0.927168L9.20148 1.92759ZM14.6173 7.61692V16.0817H16.1173V7.61692H14.6173ZM15.3673 15.3317H2.63265V16.8317H15.3673V15.3317ZM10.5361 2.96955C12.7141 2.96955 14.6173 4.96994 14.6173 7.61692H16.1173C16.1173 4.30213 13.6945 1.46955 10.5361 1.46955V2.96955ZM9.86339 2.66707C10.0262 2.84894 10.266 2.96955 10.5361 2.96955V1.46955C10.7208 1.46955 10.8787 1.55225 10.981 1.66665L9.86339 2.66707ZM8.47199 1.92759C8.68395 1.6908 8.98952 1.6908 9.20148 1.92759L10.3191 0.927168C9.51094 0.0242783 8.16253 0.0242765 7.35434 0.927167L8.47199 1.92759ZM7.14182 2.96955C7.40911 2.96955 7.64615 2.85021 7.80693 2.67058L6.68928 1.67016C6.79369 1.55352 6.95427 1.46955 7.14182 1.46955V2.96955ZM3.38265 7.25709C3.38265 4.80884 5.14168 2.96955 7.14182 2.96955V1.46955C4.16127 1.46955 1.88265 4.14104 1.88265 7.25709H3.38265Z" />
</svg>
`;
  export const WatsonGrey7 = () : string => `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="12" cy="12" r="9" stroke-width="1.5"/>
<path d="M12 7.5V12.4172C12 12.4702 12.0211 12.5211 12.0586 12.5586L14.5 15" stroke-width="1.5" stroke-linecap="round"/>
</svg>
`;
  export const WatsonGrey8 = () : string => `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M17 7L7 17" stroke-width="1.5" stroke-linecap="round"/>
<path d="M7 7L17 17" stroke-width="1.5" stroke-linecap="round"/>
</svg>
`;
  export const WatsonGrey9 = () : string => `<svg width="17" height="16" viewBox="0 0 17 16" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="7.22268" cy="7.26467" r="6.19436" stroke-width="1.3" stroke-linecap="round"/>
<path d="M12.1762 11.4177L15.5 14.5002" stroke-width="1.3" stroke-linecap="round"/>
</svg>
`;
  